### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tharun-d** [ardanlabs/mapstructure#1]
can i convert interface{} or []interface{} to []model

**Comment by ardan-bkennedy** [comment]
No since they are of different types. it would help to know more about what you are doing?

**Comment by tharun-d** [comment]
This package converts map[string]interface{} to struct.

I am trying to convert direct interface{} to struct.

That interface{} is nothing but map[string]interface{} only.

**Comment by ardan-bkennedy** [comment]
So these type assertions have to be accurate. Trying to work with a raw map[string]interface{} that has JSON is tedious. If you can define a Go struct that is better. This is what this package is trying to provide support for.

Give a variable of type `interface{}` named `a` and a struct type named `type Example struct`

The type assertion syntax of

`e, ok := a.(Example)`

would allow you to get a copy of the `Example` value inside of `a` and assigned to variable `e` with `ok` being `true`. If `ok` is `false`, then there was not a value of type `Example` inside of `a`
